//DATA e ORA in formato ISO_8601

#define PORTA_CONTROLLER 0x70
#define PORTA_DATI 0x71

#define SECONDI 0x00
#define MINUTI 0x02
#define ORE 0x04

#define GIORNO_MESE 0x07
#define MESE 0x08

#define ANNO_INIZIO 1970
#define ANNO_DECINE 0x09
#define ANNO_MIGLIAIA 0x32

void data_ora (){	
	
	outb(PORTA_CONTROLLER, ORE);
	printhex(inb(PORTA_DATI) + ANNO_INIZIO, VGA_TEXT_BIANCO_NERO);
	printchar(':', VGA_TEXT_BIANCO_NERO);

	outb(PORTA_CONTROLLER, MINUTI);
	printint(inb(PORTA_DATI) + ANNO_INIZIO, VGA_TEXT_BIANCO_NERO);
	printchar(':', VGA_TEXT_BIANCO_NERO);

	outb(PORTA_CONTROLLER, SECONDI);
	printint(inb(PORTA_DATI) + ANNO_INIZIO, VGA_TEXT_BIANCO_NERO);
	printchar('\t', VGA_TEXT_BIANCO_NERO);

	outb(PORTA_CONTROLLER, ANNO_DECINE);
	printint(hex_to_int(inb(PORTA_DATI)) + ANNO_INIZIO, VGA_TEXT_BIANCO_NERO);	
	printchar('/', VGA_TEXT_BIANCO_NERO);

	outb(PORTA_CONTROLLER, MESE);
	printint(inb(PORTA_DATI), VGA_TEXT_BIANCO_NERO);
	printchar('/', VGA_TEXT_BIANCO_NERO);

	outb(PORTA_CONTROLLER, GIORNO_MESE);
	printint(inb(PORTA_DATI), VGA_TEXT_BIANCO_NERO);

	printchar('\n', VGA_TEXT_BIANCO_NERO);
}
